# Generated by Django 5.2.12 on 2026-07-31 05:40

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0006_yearpromotionlog_students_promoted_without_results_and_more'),
        ('exams', '0005_alter_assessmenttype_unique_together_and_more'),
        ('schools', '0014_school_pass_mark_alter_school_grade_scale'),
        ('staff', '0003_rename_staff_staff_staff_i_2f5c1a_idx_staff_staff_staff_i_d27e17_idx_and_more'),
        ('students', '0005_student_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('term', 'Term Report Card'), ('cumulative', 'Year-End Cumulative Report Card')], max_length=12)),
                ('status', models.CharField(choices=[('draft', 'Draft — not visible to parents'), ('released', 'Released — visible to parents')], default='draft', max_length=10)),
                ('grade', models.IntegerField()),
                ('section', models.CharField(blank=True, max_length=10)),
                ('homeroom_teacher_name', models.CharField(blank=True, max_length=200)),
                ('overall_average', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('is_passing', models.BooleanField(blank=True, null=True)),
                ('letter_grade', models.CharField(blank=True, max_length=5)),
                ('homeroom_rank', models.PositiveIntegerField(blank=True, null=True)),
                ('homeroom_rank_total', models.PositiveIntegerField(blank=True, null=True)),
                ('school_rank', models.PositiveIntegerField(blank=True, null=True)),
                ('school_rank_total', models.PositiveIntegerField(blank=True, null=True)),
                ('attendance_present_days', models.PositiveIntegerField(blank=True, null=True)),
                ('attendance_absent_days', models.PositiveIntegerField(blank=True, null=True)),
                ('attendance_late_days', models.PositiveIntegerField(blank=True, null=True)),
                ('snapshot_data', models.JSONField(blank=True, default=dict)),
                ('homeroom_comment', models.TextField(blank=True, help_text="Homeroom teacher's free-text remark, shown on the report card.")),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='report_cards/%Y/%m/')),
                ('access_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_cards', to='academics.academicyear')),
                ('comment_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_card_comments', to='staff.staffmember')),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_cards_generated', to='staff.staffmember')),
                ('released_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_cards_released', to='staff.staffmember')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_cards', to='schools.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_cards', to='students.student')),
                ('term', models.ForeignKey(blank=True, help_text='Set for term report cards. Left blank for a year-end cumulative report card.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report_cards', to='exams.term')),
            ],
            options={
                'ordering': ['-generated_at'],
                'indexes': [models.Index(fields=['school', 'academic_year', 'grade', 'section'], name='report_card_school__a5e732_idx'), models.Index(fields=['student', 'academic_year'], name='report_card_student_b77171_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('report_type', 'term')), fields=('student', 'term'), name='unique_term_report_card'), models.UniqueConstraint(condition=models.Q(('report_type', 'cumulative')), fields=('student', 'academic_year'), name='unique_cumulative_report_card')],
            },
        ),
    ]
