# Generated by Django 5.2.12 on 2026-08-16 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0007_subject_grade_alter_subject_options_and_more'),
        ('exams', '0007_semester_term_semester_studentsemesterresult_and_more'),
        ('report_cards', '0001_initial'),
        ('schools', '0018_school_term_structure'),
        ('staff', '0004_staff_hr_module'),
        ('students', '0006_studentdocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportcard',
            name='semester',
            field=models.ForeignKey(blank=True, help_text='Set for semester report cards (quarter-structure schools only). Left blank otherwise.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report_cards', to='exams.semester'),
        ),
        migrations.AlterField(
            model_name='reportcard',
            name='report_type',
            field=models.CharField(choices=[('term', 'Term Report Card'), ('semester', 'Semester Report Card'), ('cumulative', 'Year-End Cumulative Report Card')], max_length=12),
        ),
        migrations.AddConstraint(
            model_name='reportcard',
            constraint=models.UniqueConstraint(condition=models.Q(('report_type', 'semester')), fields=('student', 'semester'), name='unique_semester_report_card'),
        ),
    ]
