# Generated by Django 5.2.12 on 2026-05-01 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_passwordhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='otp_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='otp_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='otp_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('school_admin', 'School Admin'), ('staff', 'Staff'), ('parent', 'Parent')], default='staff', max_length=20),
        ),
    ]
