# Generated by Django 5.2.12 on 2026-05-12 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_create_super_admin'),
        ('authentication', '0003_userprofile_otp_code_userprofile_otp_created_at_and_more'),
    ]

    operations = [
    ]
