# Generated by Django 5.2.12 on 2026-07-10 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_alter_student_grade_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='photo',
            field=models.ImageField(
                blank=True,
                help_text='Student profile photo (JPG, PNG)',
                null=True,
                upload_to='student_photos/%Y/%m/',
            ),
        ),
    ]
