# Generated by Django 5.2.12 on 2026-08-05 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_student_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('birth_certificate', 'Birth Certificate'), ('leaving_certificate_grade6', 'Grade 6 Leaving Certificate'), ('leaving_certificate_grade8', 'Grade 8 Leaving Certificate'), ('transfer_certificate', 'Transfer Certificate'), ('grade12_certificate', 'Grade 12 Certificate'), ('other', 'Other')], max_length=40)),
                ('file', models.FileField(help_text='Scanned copy or photo of the document (PDF, JPG, PNG)', upload_to='student_documents/%Y/%m/')),
                ('verified', models.BooleanField(default=False)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='students.student')),
            ],
            options={
                'ordering': ['-uploaded_at'],
                'indexes': [models.Index(fields=['student', 'document_type'], name='students_st_student_7712b0_idx')],
            },
        ),
    ]
