# Generated by hand (no local Django available in the sandbox this was
# written in) — modeled directly on the style of
# students/migrations/0006_studentdocument.py. Review before applying,
# same as any migration, but every field here is either nullable/blank
# or has a safe default, so this should apply cleanly to existing data
# with zero rows needing backfill.

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_studentdocument'),
        ('academics', '0007_subject_grade_alter_subject_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdocument',
            name='custom_label',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='studentdocument',
            name='academic_year',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='student_documents',
                to='academics.academicyear',
            ),
        ),
        migrations.AddField(
            model_name='studentdocument',
            name='status',
            field=models.CharField(
                choices=[('pending', 'Pending Review'), ('verified', 'Verified'), ('rejected', 'Rejected')],
                default='pending',
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name='studentdocument',
            name='review_note',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='studentdocument',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentdocument',
            name='document_type',
            field=models.CharField(
                choices=[
                    ('birth_certificate', 'Birth Certificate'),
                    ('leaving_certificate_grade6', 'Grade 6 Leaving Certificate'),
                    ('leaving_certificate_grade8', 'Grade 8 Leaving Certificate'),
                    ('transfer_certificate', 'Transfer Certificate'),
                    ('grade12_certificate', 'Grade 12 Certificate'),
                    ('educational_document', 'Educational Document (Yearly)'),
                    ('other', 'Other'),
                ],
                max_length=40,
            ),
        ),
        migrations.CreateModel(
            name='RequiredDocumentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(
                    choices=[
                        ('birth_certificate', 'Birth Certificate'),
                        ('leaving_certificate_grade6', 'Grade 6 Leaving Certificate'),
                        ('leaving_certificate_grade8', 'Grade 8 Leaving Certificate'),
                        ('transfer_certificate', 'Transfer Certificate'),
                        ('grade12_certificate', 'Grade 12 Certificate'),
                        ('educational_document', 'Educational Document (Yearly)'),
                        ('other', 'Other'),
                    ],
                    max_length=40,
                )),
                ('custom_label', models.CharField(
                    blank=True,
                    help_text="Required when document_type is 'other' — e.g. 'Kebele ID letter'",
                    max_length=100,
                )),
                ('note', models.CharField(
                    blank=True,
                    help_text='Shown to the parent — why this document is needed',
                    max_length=255,
                )),
                ('requested_by', models.CharField(blank=True, max_length=150)),
                ('is_resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('student', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='document_requests',
                    to='students.student',
                )),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
