# Generated by Django 5.2.12 on 2026-04-09 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='logo',
            field=models.ImageField(blank=True, help_text='School logo (JPG, PNG)', null=True, upload_to='school_logos/'),
        ),
    ]
