# Generated by Django 5.2.12 on 2026-06-07 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0003_schooladminprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='at_api_key',
            field=models.CharField(blank=True, help_text="Africa's Talking API key", max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='at_username',
            field=models.CharField(blank=True, help_text="Africa's Talking username (e.g., sandbox or your username)", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='sms_current_month_count',
            field=models.IntegerField(default=0, help_text='SMS sent this month'),
        ),
        migrations.AddField(
            model_name='school',
            name='sms_enabled',
            field=models.BooleanField(default=False, help_text='Is SMS configured and working?'),
        ),
        migrations.AddField(
            model_name='school',
            name='sms_last_reset',
            field=models.DateField(blank=True, help_text='Last time monthly counter was reset', null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='sms_last_test',
            field=models.DateTimeField(blank=True, help_text='Last time SMS credentials were tested', null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='sms_monthly_limit',
            field=models.IntegerField(default=0, help_text='Monthly SMS limit (0 = unlimited)'),
        ),
        migrations.AddField(
            model_name='school',
            name='sms_sender_id',
            field=models.CharField(blank=True, help_text="SMS sender ID (max 11 chars) - must be approved by Africa's Talking", max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='sms_test_status',
            field=models.CharField(blank=True, help_text='Status of last test (success/failed/pending)', max_length=50, null=True),
        ),
    ]
