# Generated by Django 5.2.12 on 2026-06-12 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0004_school_at_api_key_school_at_username_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='cbe_account_number',
            field=models.CharField(blank=True, help_text="School's CBE account number (e.g., 1000137267900)", max_length=50),
        ),
        migrations.AddField(
            model_name='school',
            name='cbe_account_suffix',
            field=models.CharField(blank=True, help_text='Last 8 digits of CBE account (e.g., 13726790)', max_length=8),
        ),
        migrations.AddField(
            model_name='school',
            name='verify_et_api_key',
            field=models.CharField(blank=True, help_text='Verify.ET API key for this school (from https://verify.et)', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='verify_et_enabled',
            field=models.BooleanField(default=False, help_text='Is Verify.ET API configured and working for this school?'),
        ),
        migrations.AddField(
            model_name='school',
            name='verify_et_last_test',
            field=models.DateTimeField(blank=True, help_text='Last time Verify.ET API credentials were tested', null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='verify_et_test_status',
            field=models.CharField(blank=True, help_text='Status of last API test (success/failed/pending)', max_length=50),
        ),
    ]
