# Generated by Django 5.2.12 on 2026-06-17 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0005_school_cbe_account_number_school_cbe_account_suffix_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='chapa_api_key',
            field=models.CharField(blank=True, help_text='Chapa API key (starts with CHASECK_)', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='chapa_enabled',
            field=models.BooleanField(default=False, help_text='Is Chapa configured and working for this school?'),
        ),
        migrations.AddField(
            model_name='school',
            name='chapa_last_test',
            field=models.DateTimeField(blank=True, help_text='Last time Chapa credentials were tested', null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='chapa_test_status',
            field=models.CharField(blank=True, help_text='Status of last Chapa test (success/failed/pending)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='chapa_webhook_secret',
            field=models.CharField(blank=True, help_text='Chapa webhook secret for verifying webhook requests', max_length=200, null=True),
        ),
    ]
