# Generated by Django 5.2.12 on 2026-07-03 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0006_school_chapa_api_key_school_chapa_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='brevo_api_key',
            field=models.CharField(blank=True, help_text="Brevo v3 API key for this school's transactional emails", max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='brevo_sender_email',
            field=models.EmailField(blank=True, help_text='Verified sender email in Brevo (e.g., finance@school.edu.et)', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='brevo_sender_name',
            field=models.CharField(blank=True, help_text='Sender name displayed in emails (e.g., Greenfield Academy)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='email_current_month_count',
            field=models.IntegerField(default=0, help_text='Emails sent this month'),
        ),
        migrations.AddField(
            model_name='school',
            name='email_enabled',
            field=models.BooleanField(default=False, help_text='Is school email configured and working?'),
        ),
        migrations.AddField(
            model_name='school',
            name='email_last_reset',
            field=models.DateField(blank=True, help_text='Last time monthly counter was reset', null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='email_last_test',
            field=models.DateTimeField(blank=True, help_text='Last time email credentials were tested', null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='email_monthly_limit',
            field=models.IntegerField(default=0, help_text='Monthly email limit (0 = unlimited)'),
        ),
        migrations.AddField(
            model_name='school',
            name='email_test_status',
            field=models.CharField(blank=True, help_text='Status of last test (success/failed/pending)', max_length=50, null=True),
        ),
    ]
