# Generated by Django 5.2.12 on 2026-07-03 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0007_school_brevo_api_key_school_brevo_sender_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='email_test_status',
            field=models.CharField(blank=True, help_text='Status of last test (success/failed/pending)', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='sms_test_status',
            field=models.CharField(blank=True, help_text='Status of last test (success/failed/pending)', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='verify_et_test_status',
            field=models.CharField(blank=True, help_text='Status of last API test (success/failed/pending)', max_length=255),
        ),
    ]
