# Generated by Django 5.2.12 on 2026-07-04 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0008_alter_school_email_test_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='at_api_key',
            field=models.CharField(blank=True, help_text='SMSEthiopia API Key', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='at_username',
            field=models.CharField(blank=True, help_text='SMSEthiopia Campaign Name or Username (Optional)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='brevo_api_key',
            field=models.CharField(blank=True, help_text='Brevo v3 API key for transactional emails', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='brevo_sender_email',
            field=models.EmailField(blank=True, help_text='Verified sender email in Brevo', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='brevo_sender_name',
            field=models.CharField(blank=True, help_text='Sender display name (e.g., Greenfield Academy)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='cbe_account_number',
            field=models.CharField(blank=True, help_text="School's CBE account number", max_length=50),
        ),
        migrations.AlterField(
            model_name='school',
            name='cbe_account_suffix',
            field=models.CharField(blank=True, help_text='Last 8 digits of CBE account', max_length=8),
        ),
        migrations.AlterField(
            model_name='school',
            name='chapa_test_status',
            field=models.CharField(blank=True, help_text='Status of Chapa test (success/failed/pending)', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='email_test_status',
            field=models.CharField(blank=True, help_text='Status of last email test (success/failed/pending)', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='sms_sender_id',
            field=models.CharField(blank=True, help_text='SMS Sender ID (max 11 chars) - e.g., SCHOOLPAY', max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='verify_et_api_key',
            field=models.CharField(blank=True, help_text='Verify.ET API key for this school', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='verify_et_enabled',
            field=models.BooleanField(default=False, help_text='Is Verify.ET API configured and working?'),
        ),
    ]
