# Generated by Django 5.2.12 on 2026-07-04 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0009_alter_school_at_api_key_alter_school_at_username_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='at_api_key',
            field=models.CharField(blank=True, help_text='SMSEthiopia API Key', max_length=512, null=True),
        ),
    ]
