# Generated by Django 5.2.12 on 2026-07-10 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0010_alter_school_at_api_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='grading_system',
            field=models.CharField(
                choices=[
                    ('percentage', 'Percentage (out of 100)'),
                    ('letter_grade', 'Letter Grade (A, B, C...)'),
                    ('both', 'Both (show percentage and letter grade)'),
                ],
                default='percentage',
                help_text='How this school grades and displays exam results',
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name='school',
            name='grade_scale',
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Letter grade boundaries, e.g. [{'min': 90, 'max': 100, 'grade': 'A'}, ...]. Ignored if grading_system is 'percentage'.",
            ),
        ),
    ]
