# Generated by Django 5.2.12 on 2026-07-24 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0011_school_grading_system_school_grade_scale'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='subscription_status',
            field=models.CharField(
                choices=[
                    ('pending', 'Pending Approval'),
                    ('approved', 'Approved'),
                    ('rejected', 'Rejected'),
                    ('suspended', 'Suspended'),
                ],
                default='approved',
                max_length=20,
                help_text='Existing schools default to approved so nobody currently using the system gets locked out. New signups should be created with pending explicitly.',
            ),
        ),
    ]
