# Generated by Django 5.2.12 on 2026-07-24 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0012_school_subscription_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='subscription_status',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('suspended', 'Suspended')], default='approved', max_length=20),
        ),
    ]
