# Generated by Django 5.2.12 on 2026-07-28 14:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0013_alter_school_subscription_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='pass_mark',
            field=models.DecimalField(decimal_places=2, default=50, help_text="Minimum percentage to pass a subject/term. Used when grading_system is 'percentage' or 'both'; ignored for 'letter_grade'.", max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='school',
            name='grade_scale',
            field=models.JSONField(blank=True, default=list, help_text="Letter grade boundaries, e.g. [{'min': 90, 'max': 100, 'grade': 'A', 'is_passing': true}, ...]. The 'is_passing' flag on each band is what Phase 4 pass/fail uses when grading_system is 'letter_grade' — schools mark which bands count as a pass (e.g. F is not passing). Ignored if grading_system is 'percentage'."),
        ),
    ]
