# Generated by hand to match the project's existing migration style
# (Django 5.2.12)

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0015_schoolbankaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='naming_convention',
            field=models.CharField(
                choices=[
                    ('ethiopian', 'Ethiopian (First Name + Father Name)'),
                    ('international', 'International (First Name + Last Name)'),
                ],
                default='ethiopian',
                help_text='How student names are displayed/printed on ID cards, report cards and receipts.',
                max_length=20,
            ),
        ),
    ]
