# Generated by Django 5.2.12 on 2026-08-16 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0017_school_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='term_structure',
            field=models.CharField(choices=[('semester', 'Semesters only (no quarters)'), ('quarter', 'Quarters grouped into semesters')], default='semester', help_text="'semester' = this school's Terms are used as-is, ungrouped (today's behavior — 2 semesters, 3 trimesters, etc). 'quarter' = this school's 4 Terms are grouped in pairs into 2 Semesters, unlocking semester-level results, ranking and report cards. Should be locked once the current academic year already has Terms set up — switching mid-year is not supported.", max_length=20),
        ),
    ]
