# Generated by Django 5.2.12 on 2026-08-18 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0018_school_term_structure'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='director_signature',
            field=models.ImageField(blank=True, help_text="Director/principal's signature image, printed on report cards (JPG, PNG).", null=True, upload_to='school_signatures/'),
        ),
        migrations.AddField(
            model_name='school',
            name='school_stamp',
            field=models.ImageField(blank=True, help_text='Official school stamp/seal image, printed on report cards (JPG, PNG).', null=True, upload_to='school_stamps/'),
        ),
    ]
