# Generated by Django 5.2.12 on 2026-03-11 06:31

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_ec', models.IntegerField(help_text='Ethiopian Calendar year (e.g., 2016)', unique=True, validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2100)])),
                ('name', models.CharField(help_text='e.g., 2016 E.C.', max_length=50)),
                ('start_date', models.DateField(help_text='When the academic year starts')),
                ('end_date', models.DateField(help_text='When the academic year ends')),
                ('is_current', models.BooleanField(default=False, help_text='Is this the current academic year?')),
                ('is_active', models.BooleanField(default=True, help_text='Is this year active in the system?')),
                ('total_students', models.IntegerField(default=0)),
                ('total_payments', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Academic Year',
                'verbose_name_plural': 'Academic Years',
                'ordering': ['-year_ec'],
            },
        ),
        migrations.CreateModel(
            name='YearPromotionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('students_promoted', models.IntegerField(default=0)),
                ('students_graduated', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions_from', to='academics.academicyear')),
                ('promoted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('to_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions_to', to='academics.academicyear')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
