# Generated by Django 5.2.12 on 2026-04-12 10:34

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
        ('schools', '0002_school_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicyear',
            name='school',
            field=models.ForeignKey(blank=True, help_text='School this academic year belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='academic_years', to='schools.school'),
        ),
        migrations.AlterField(
            model_name='academicyear',
            name='is_current',
            field=models.BooleanField(default=False, help_text='Is this the current academic year for this school?'),
        ),
        migrations.AlterField(
            model_name='academicyear',
            name='year_ec',
            field=models.IntegerField(help_text='Ethiopian Calendar year (e.g., 2016)', validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2100)]),
        ),
        migrations.AlterUniqueTogether(
            name='academicyear',
            unique_together={('school', 'year_ec')},
        ),
    ]
