# Generated by Django 5.2.12 on 2026-05-01 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_academicyear_school_alter_academicyear_is_current_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicyear',
            name='is_current',
            field=models.BooleanField(default=False, help_text='Is this the current academic year?'),
        ),
    ]
