# Generated by Django 5.2.12 on 2026-05-05 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_alter_academicyear_is_current'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicyear',
            name='is_archived',
            field=models.BooleanField(default=False, help_text='Soft delete flag'),
        ),
    ]
