# Generated by Django 5.2.12 on 2026-07-17 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_academicyear_is_archived'),
        ('schools', '0011_school_grading_system_school_grade_scale'),
        ('staff', '0001_initial'),
        ('students', '0005_student_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeroomAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homeroom_assignments', to='academics.academicyear')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homeroom_assignments', to='schools.school')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homeroom_assignments', to='students.section')),
                ('teacher', models.ForeignKey(limit_choices_to={'role': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, related_name='homeroom_assignments', to='staff.staffmember')),
            ],
            options={
                'ordering': ['grade', 'section__name'],
                'unique_together': {('school', 'academic_year', 'grade', 'section')},
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., English, Mathematics, Physics', max_length=100)),
                ('code', models.CharField(blank=True, help_text='Optional short code, e.g., ENG, MATH, PHY', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='schools.school')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('school', 'name')},
            },
        ),
    ]
