# Generated by Django 5.2.12 on 2026-08-06 00:00
# ✅ Subjects are now class(grade)-based: a school can register the same
# subject name once per grade (e.g. "Mathematics" for Grade 1 AND for
# Grade 9), or leave grade blank to keep a subject available to every
# grade — matching every existing subject's behavior unchanged.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0006_yearpromotionlog_students_promoted_without_results_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='grade',
            field=models.IntegerField(
                blank=True,
                choices=[(1, 'Grade 1'), (2, 'Grade 2'), (3, 'Grade 3'), (4, 'Grade 4'),
                         (5, 'Grade 5'), (6, 'Grade 6'), (7, 'Grade 7'), (8, 'Grade 8'),
                         (9, 'Grade 9'), (10, 'Grade 10'), (11, 'Grade 11'), (12, 'Grade 12')],
                help_text='Leave blank to make this subject available to every grade',
                null=True,
            ),
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['grade', 'name']},
        ),
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together={('school', 'name', 'grade')},
        ),
    ]
