# Generated by Django 5.2.12 on 2026-07-18 13:02

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0005_homeroomassignment_subject'),
        ('schools', '0011_school_grading_system_school_grade_scale'),
        ('staff', '0002_alter_teacherclassassignment_options_and_more'),
        ('students', '0005_student_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., Mid Term Exam, Final Exam, Quiz 1', max_length=100)),
                ('max_score', models.DecimalField(decimal_places=2, default=100, help_text='The score this assessment is out of, e.g. 100 or 50', max_digits=6, validators=[django.core.validators.MinValueValidator(1)])),
                ('weight_percent', models.DecimalField(blank=True, decimal_places=2, help_text='Optional — how much this counts toward the final grade (e.g. Final Exam = 40%). Leave blank if not using weighted grading yet.', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('order', models.IntegerField(default=0, help_text='Controls display order')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_types', to='academics.academicyear')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_types', to='schools.school')),
            ],
            options={
                'ordering': ['order', 'name'],
                'unique_together': {('school', 'academic_year', 'name')},
            },
        ),
        migrations.CreateModel(
            name='DailyAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.IntegerField()),
                ('section', models.CharField(blank=True, max_length=10)),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late'), ('excused', 'Excused')], default='present', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='academics.academicyear')),
                ('recorded_by', models.ForeignKey(limit_choices_to={'role': 'teacher'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_recorded', to='staff.staffmember')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='schools.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='students.student')),
            ],
            options={
                'ordering': ['-date', 'student__first_name'],
                'indexes': [models.Index(fields=['school', 'academic_year', 'grade', 'section', 'date'], name='exams_daily_school__6df5d6_idx')],
                'unique_together': {('student', 'date')},
            },
        ),
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.IntegerField()),
                ('section', models.CharField(blank=True, max_length=10)),
                ('score', models.DecimalField(blank=True, decimal_places=2, help_text='Null until the subject teacher enters it', max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted — awaiting homeroom review'), ('accepted', 'Accepted by homeroom'), ('rejected', 'Sent back by homeroom')], default='draft', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('homeroom_note', models.TextField(blank=True, help_text='Optional note from homeroom, e.g. why a mark was sent back')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='academics.academicyear')),
                ('assessment_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='exams.assessmenttype')),
                ('entered_by', models.ForeignKey(limit_choices_to={'role': 'teacher'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marks_entered', to='staff.staffmember')),
                ('reviewed_by', models.ForeignKey(blank=True, help_text='The homeroom teacher who accepted/rejected this', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marks_reviewed', to='staff.staffmember')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='schools.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='students.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='academics.subject')),
            ],
            options={
                'ordering': ['student__first_name', 'subject__name'],
                'indexes': [models.Index(fields=['school', 'academic_year', 'grade', 'section'], name='exams_mark_school__a21675_idx'), models.Index(fields=['subject', 'assessment_type', 'status'], name='exams_mark_subject_4fc513_idx')],
                'unique_together': {('student', 'subject', 'assessment_type')},
            },
        ),
    ]
