# Generated by Django 5.2.12 on 2026-07-23 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_homeroomassignment_subject'),
        ('exams', '0001_initial'),
        ('schools', '0011_school_grading_system_school_grade_scale'),
        ('staff', '0002_alter_teacherclassassignment_options_and_more'),
        ('students', '0005_student_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., Semester 1, Semester 2, Trimester 1', max_length=50)),
                ('order', models.IntegerField(default=0, help_text='Controls display order — 1st term, 2nd term...')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terms', to='academics.academicyear')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terms', to='schools.school')),
            ],
            options={
                'ordering': ['order', 'name'],
                'unique_together': {('school', 'academic_year', 'name')},
            },
        ),
        migrations.AddField(
            model_name='assessmenttype',
            name='term',
            field=models.ForeignKey(blank=True, help_text='Which term this belongs to, e.g. Semester 1', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assessment_types', to='exams.term'),
        ),
        migrations.CreateModel(
            name='SubjectAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.IntegerField()),
                ('section', models.CharField(blank=True, max_length=10)),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late'), ('excused', 'Excused')], default='present', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_attendance_records', to='academics.academicyear')),
                ('recorded_by', models.ForeignKey(limit_choices_to={'role': 'teacher'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subject_attendance_recorded', to='staff.staffmember')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_attendance_records', to='schools.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_attendance_records', to='students.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='academics.subject')),
            ],
            options={
                'ordering': ['-date', 'student__first_name'],
                'indexes': [models.Index(fields=['school', 'academic_year', 'subject', 'grade', 'section', 'date'], name='exams_subje_school__a08532_idx')],
                'unique_together': {('student', 'subject', 'date')},
            },
        ),
    ]
