# Generated by Django 5.2.12 on 2026-07-28 14:30

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_homeroomassignment_subject'),
        ('exams', '0002_term_assessmenttype_term_subjectattendance'),
        ('schools', '0014_school_pass_mark_alter_school_grade_scale'),
        ('staff', '0003_rename_staff_staff_staff_i_2f5c1a_idx_staff_staff_staff_i_d27e17_idx_and_more'),
        ('students', '0005_student_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentTermResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.IntegerField()),
                ('section', models.CharField(blank=True, max_length=10)),
                ('overall_average', models.DecimalField(blank=True, decimal_places=2, help_text="Simple average of this student's SubjectTermResult.average_percentage values for this term.", max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('subjects_counted', models.PositiveIntegerField(default=0)),
                ('is_passing', models.BooleanField(blank=True, null=True)),
                ('letter_grade', models.CharField(blank=True, help_text="Set only when the school's grading_system is 'letter_grade' or 'both'.", max_length=5)),
                ('homeroom_rank', models.PositiveIntegerField(blank=True, null=True)),
                ('homeroom_rank_total', models.PositiveIntegerField(blank=True, help_text="Class size used to produce homeroom_rank, e.g. '3rd of 42'.", null=True)),
                ('school_rank', models.PositiveIntegerField(blank=True, null=True)),
                ('school_rank_total', models.PositiveIntegerField(blank=True, null=True)),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_term_results', to='academics.academicyear')),
                ('computed_by', models.ForeignKey(blank=True, help_text='Who triggered the last recalculation, e.g. the homeroom teacher or an admin.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='term_results_computed', to='staff.staffmember')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_term_results', to='schools.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='term_results', to='students.student')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_results', to='exams.term')),
            ],
            options={
                'ordering': ['-overall_average'],
                'indexes': [models.Index(fields=['school', 'academic_year', 'term', 'grade', 'section'], name='exams_stude_school__bc67c8_idx'), models.Index(fields=['school', 'academic_year', 'term'], name='exams_stude_school__084424_idx')],
                'unique_together': {('student', 'term')},
            },
        ),
        migrations.CreateModel(
            name='SubjectTermResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.IntegerField()),
                ('section', models.CharField(blank=True, max_length=10)),
                ('average_percentage', models.DecimalField(blank=True, decimal_places=2, help_text="Simple average of this student's accepted marks for this subject/term, each normalized to a percentage of its assessment's max_score.", max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('marks_counted', models.PositiveIntegerField(default=0, help_text='How many accepted Mark rows fed into average_percentage.')),
                ('is_passing', models.BooleanField(blank=True, null=True)),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_term_results', to='academics.academicyear')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_term_results', to='schools.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_term_results', to='students.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='term_results', to='academics.subject')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_results', to='exams.term')),
            ],
            options={
                'indexes': [models.Index(fields=['school', 'academic_year', 'term', 'grade', 'section'], name='exams_subje_school__c12fbf_idx')],
                'unique_together': {('student', 'subject', 'term')},
            },
        ),
    ]
