# Generated by Django 5.2.12 on 2026-07-30 06:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_studenttermresult_subjecttermresult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjecttermresult',
            name='average_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Sum of accepted Mark scores for this subject/term divided by the sum of their max_scores, as a percentage — matches the gradebook's Total/100 column.", max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
