# Generated by Django 5.2.12 on 2026-07-30 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_homeroomassignment_subject'),
        ('exams', '0004_alter_subjecttermresult_average_percentage'),
        ('schools', '0014_school_pass_mark_alter_school_grade_scale'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='assessmenttype',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='assessmenttype',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('school', 'academic_year', 'term', 'name'), name='unique_active_assessment_type_per_term'),
        ),
    ]
