# Generated by Django 5.2.12 on 2026-08-06 00:00
# ✅ Assessment types are now class(grade)-based: a school can register
# the same name once per grade within a term (e.g. "Assignment" for
# Grade 1 AND separately for Grade 10), or leave grade blank to keep an
# assessment type applying to every grade — matching every existing
# assessment type's behavior unchanged.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0005_alter_assessmenttype_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmenttype',
            name='grade',
            field=models.IntegerField(
                blank=True,
                choices=[(1, 'Grade 1'), (2, 'Grade 2'), (3, 'Grade 3'), (4, 'Grade 4'),
                         (5, 'Grade 5'), (6, 'Grade 6'), (7, 'Grade 7'), (8, 'Grade 8'),
                         (9, 'Grade 9'), (10, 'Grade 10'), (11, 'Grade 11'), (12, 'Grade 12')],
                help_text='Leave blank to make this assessment type available to every grade',
                null=True,
            ),
        ),
        migrations.RemoveConstraint(
            model_name='assessmenttype',
            name='unique_active_assessment_type_per_term',
        ),
        migrations.AddConstraint(
            model_name='assessmenttype',
            constraint=models.UniqueConstraint(
                condition=models.Q(('is_active', True)),
                fields=('school', 'academic_year', 'term', 'name', 'grade'),
                name='unique_active_assessment_type_per_term',
            ),
        ),
    ]
