# Generated by Django 5.2.12 on 2026-08-16 15:47

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0007_subject_grade_alter_subject_options_and_more'),
        ('exams', '0006_assessmenttype_grade_and_more'),
        ('schools', '0018_school_term_structure'),
        ('staff', '0004_staff_hr_module'),
        ('students', '0006_studentdocument'),
    ]

    operations = [
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., Semester 1, Semester 2', max_length=50)),
                ('order', models.IntegerField(default=0, help_text='Controls display order — 1st semester, 2nd semester...')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semesters', to='academics.academicyear')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semesters', to='schools.school')),
            ],
            options={
                'ordering': ['order', 'name'],
                'unique_together': {('school', 'academic_year', 'name')},
            },
        ),
        migrations.AddField(
            model_name='term',
            name='semester',
            field=models.ForeignKey(blank=True, help_text='Which Semester this Term belongs to. Only used by quarter-structure schools — leave blank otherwise.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='terms', to='exams.semester'),
        ),
        migrations.CreateModel(
            name='StudentSemesterResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.IntegerField()),
                ('section', models.CharField(blank=True, max_length=10)),
                ('overall_average', models.DecimalField(blank=True, decimal_places=2, help_text="Simple average of this student's SubjectSemesterResult.average_percentage values for this semester.", max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('subjects_counted', models.PositiveIntegerField(default=0)),
                ('is_passing', models.BooleanField(blank=True, null=True)),
                ('letter_grade', models.CharField(blank=True, help_text="Set only when the school's grading_system is 'letter_grade' or 'both'.", max_length=5)),
                ('homeroom_rank', models.PositiveIntegerField(blank=True, null=True)),
                ('homeroom_rank_total', models.PositiveIntegerField(blank=True, null=True)),
                ('school_rank', models.PositiveIntegerField(blank=True, null=True)),
                ('school_rank_total', models.PositiveIntegerField(blank=True, null=True)),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_semester_results', to='academics.academicyear')),
                ('computed_by', models.ForeignKey(blank=True, help_text='Who triggered the last recalculation.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='semester_results_computed', to='staff.staffmember')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_semester_results', to='schools.school')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_results', to='exams.semester')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semester_results', to='students.student')),
            ],
            options={
                'ordering': ['-overall_average'],
                'indexes': [models.Index(fields=['school', 'academic_year', 'semester', 'grade', 'section'], name='exams_stude_school__3992b9_idx'), models.Index(fields=['school', 'academic_year', 'semester'], name='exams_stude_school__e68037_idx')],
                'unique_together': {('student', 'semester')},
            },
        ),
        migrations.CreateModel(
            name='SubjectSemesterResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.IntegerField()),
                ('section', models.CharField(blank=True, max_length=10)),
                ('average_percentage', models.DecimalField(blank=True, decimal_places=2, help_text="Simple average of this subject's SubjectTermResult.average_percentage across the semester's child terms.", max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('terms_counted', models.PositiveIntegerField(default=0, help_text='How many child-term SubjectTermResult rows fed into average_percentage.')),
                ('is_passing', models.BooleanField(blank=True, null=True)),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_semester_results', to='academics.academicyear')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_semester_results', to='schools.school')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_results', to='exams.semester')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_semester_results', to='students.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semester_results', to='academics.subject')),
            ],
            options={
                'indexes': [models.Index(fields=['school', 'academic_year', 'semester', 'grade', 'section'], name='exams_subje_school__563fbc_idx')],
                'unique_together': {('student', 'subject', 'semester')},
            },
        ),
    ]
