# Generated by Django 5.2.12 on 2026-03-08 11:31

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0001_initial'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentDeadline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(max_length=20)),
                ('month', models.IntegerField(choices=[(1, 'Meskerem'), (2, 'Tikimt'), (3, 'Hidar'), (4, 'Tahsas'), (5, 'Tir'), (6, 'Yekatit'), (7, 'Megabit'), (8, 'Miazia'), (9, 'Ginbot'), (10, 'Sene'), (11, 'Hamle'), (12, 'Nehase'), (13, 'Pagume')])),
                ('due_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deadlines', to='schools.school')),
            ],
            options={
                'ordering': ['academic_year', 'month'],
                'unique_together': {('school', 'academic_year', 'month')},
            },
        ),
        migrations.CreateModel(
            name='PaymentReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('sent_to', models.CharField(max_length=20)),
                ('message', models.TextField()),
                ('status', models.CharField(max_length=20)),
                ('deadline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.paymentdeadline')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='students.student')),
            ],
            options={
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('telebirr', 'Telebirr'), ('bank_transfer', 'Bank Transfer'), ('other', 'Other')], max_length=20)),
                ('transaction_reference', models.CharField(blank=True, max_length=200)),
                ('payment_proof', models.FileField(blank=True, null=True, upload_to='payment_proofs/%Y/%m/')),
                ('status', models.CharField(choices=[('pending', 'Pending Verification'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('paid_by', models.CharField(max_length=200)),
                ('paid_by_phone', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='students.student')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_payments', to=settings.AUTH_USER_MODEL)),
                ('deadline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='payments.paymentdeadline')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='payments_pa_status_7ad4af_idx'), models.Index(fields=['transaction_reference'], name='payments_pa_transac_2dc1cb_idx'), models.Index(fields=['student', 'deadline'], name='payments_pa_student_be85d3_idx')],
            },
        ),
    ]
