# Generated by Django 5.2.12 on 2026-03-16 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_paymentslip'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentslip',
            name='ai_confidence',
            field=models.IntegerField(default=0, help_text='AI confidence score (0-100)'),
        ),
        migrations.AddField(
            model_name='paymentslip',
            name='ai_extracted_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='paymentslip',
            name='ai_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='paymentslip',
            name='ai_reviewed',
            field=models.BooleanField(default=False, help_text='Whether AI has reviewed this slip'),
        ),
        migrations.AddField(
            model_name='paymentslip',
            name='auto_verified',
            field=models.BooleanField(default=False, help_text='Whether AI auto-verified this slip'),
        ),
    ]
