# Generated by Django 5.2.12 on 2026-05-05 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_alter_paymentdeadline_month'),
        ('schools', '0003_schooladminprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentdeadline',
            options={'ordering': ['academic_year', 'month', 'grade']},
        ),
        migrations.AlterUniqueTogether(
            name='paymentdeadline',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='paymentdeadline',
            name='grade',
            field=models.IntegerField(blank=True, choices=[(1, 'Grade 1'), (2, 'Grade 2'), (3, 'Grade 3'), (4, 'Grade 4'), (5, 'Grade 5'), (6, 'Grade 6'), (7, 'Grade 7'), (8, 'Grade 8')], help_text='Leave blank to apply to all grades', null=True),
        ),
        migrations.AlterUniqueTogether(
            name='paymentdeadline',
            unique_together={('school', 'academic_year', 'month', 'grade')},
        ),
    ]
