# Generated by Django 5.2.12 on 2026-05-28 07:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_payment_chapa_reference_payment_invoice_number_and_more'),
        ('students', '0003_alter_student_student_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='deleted_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='paymentslip',
            name='ai_confidence',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='paymentslip',
            name='ai_reviewed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='paymentslip',
            name='auto_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='smshistory',
            name='related_to',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['is_deleted'], name='payments_pa_is_dele_d6524f_idx'),
        ),
    ]
