# Generated by Django 5.2.12 on 2026-05-28 08:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_payment_deleted_at_payment_deleted_reason_and_more'),
        ('students', '0003_alter_student_student_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='payment',
            name='payments_pa_is_dele_d6524f_idx',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='deleted_at',
            new_name='archived_at',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='is_deleted',
            new_name='is_archived',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='deleted_reason',
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['is_archived'], name='payments_pa_is_arch_751565_idx'),
        ),
    ]
