# Generated by Django 5.2.12 on 2026-06-08 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0009_remove_payment_payments_pa_is_dele_d6524f_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='is_from_slip',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='payment',
            name='slip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.paymentslip'),
        ),
    ]
