# Generated by Django 5.2.12 on 2026-06-11 09:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0010_payment_is_from_slip_payment_slip'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentslip',
            name='cbe_check_method',
            field=models.CharField(blank=True, choices=[('ussd', 'USSD *894#'), ('call', 'Phone Call 6294'), ('manual', 'Manual Check')], max_length=20),
        ),
        migrations.AddField(
            model_name='paymentslip',
            name='cbe_verification_notes',
            field=models.TextField(blank=True, help_text='Admin notes from CBE verification'),
        ),
        migrations.AddField(
            model_name='paymentslip',
            name='cbe_verification_status',
            field=models.CharField(choices=[('pending', 'Pending CBE Check'), ('cbe_verified', 'CBE Verified'), ('cbe_rejected', 'CBE Rejected'), ('cbe_check_failed', 'CBE Check Failed')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='paymentslip',
            name='cbe_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymentslip',
            name='cbe_verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cbe_verified_slips', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paymentslip',
            name='transaction_reference',
            field=models.CharField(blank=True, help_text='CBE transaction reference number', max_length=100),
        ),
    ]
