# Generated by Django 5.2.12 on 2026-06-12 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0011_paymentslip_cbe_check_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentslip',
            name='verify_et_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Amount from bank', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='paymentslip',
            name='verify_et_checked_at',
            field=models.DateTimeField(blank=True, help_text='When API was last called', null=True),
        ),
        migrations.AddField(
            model_name='paymentslip',
            name='verify_et_date',
            field=models.CharField(blank=True, help_text='Transaction date from bank', max_length=50),
        ),
        migrations.AddField(
            model_name='paymentslip',
            name='verify_et_error',
            field=models.TextField(blank=True, help_text='Error message if API failed'),
        ),
        migrations.AddField(
            model_name='paymentslip',
            name='verify_et_payer_name',
            field=models.CharField(blank=True, help_text='Payer name from bank', max_length=200),
        ),
        migrations.AddField(
            model_name='paymentslip',
            name='verify_et_receiver',
            field=models.CharField(blank=True, help_text='Receiver name from bank', max_length=200),
        ),
        migrations.AddField(
            model_name='paymentslip',
            name='verify_et_response_raw',
            field=models.JSONField(blank=True, default=dict, help_text='Raw API response'),
        ),
        migrations.AddField(
            model_name='paymentslip',
            name='verify_et_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('queued', 'Queued'), ('verified', 'Verified by API'), ('failed', 'Verification Failed'), ('invalid', 'Invalid Transaction'), ('timeout', 'Timeout'), ('error', 'API Error')], default='pending', help_text='Status from Verify.ET API', max_length=20),
        ),
        migrations.AlterField(
            model_name='paymentslip',
            name='cbe_check_method',
            field=models.CharField(blank=True, choices=[('ussd', 'USSD *894#'), ('call', 'Phone Call 6294'), ('manual', 'Manual Check'), ('api', 'Verify.ET API')], max_length=20),
        ),
    ]
