# Generated by Django 5.2.12 on 2026-06-19 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0012_paymentslip_verify_et_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentslip',
            name='auto_verified',
        ),
        migrations.AddField(
            model_name='paymentslip',
            name='verification_error',
            field=models.TextField(blank=True, help_text='Detailed error from background task'),
        ),
        migrations.AddField(
            model_name='paymentslip',
            name='verification_status',
            field=models.CharField(choices=[('pending', 'Pending Verification'), ('queued', 'Queued for Background Check'), ('verified', 'Verified by System'), ('failed', 'Verification Failed'), ('manual_review', 'Needs Manual Review'), ('timeout', 'Verification Timed Out')], default='pending', help_text='Current verification workflow status', max_length=20),
        ),
        migrations.AddField(
            model_name='paymentslip',
            name='verified_at_system',
            field=models.DateTimeField(blank=True, help_text='When system verification completed', null=True),
        ),
        migrations.AddField(
            model_name='paymentslip',
            name='verify_et_task_id',
            field=models.CharField(blank=True, help_text='Django-Q task ID for background verification', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='paymentdeadline',
            name='month',
            field=models.IntegerField(choices=[(1, 'መስረም'), (2, 'ጥቅምት'), (3, 'ህር'), (4, 'ታህስ'), (5, 'ጥር'), (6, 'የካቲት'), (7, 'መጋቢት'), (8, 'ሚያዝያ'), (9, 'ግንቦት'), (10, 'ሰኔ'), (11, 'ሐምሌ'), (12, 'ነሐሴ'), (13, 'ጳጉሜ')]),
        ),
    ]
