# Generated by Django 5.2.12 on 2026-06-29 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0017_cleanup_and_paymentslip_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentdeadline',
            name='month',
            field=models.IntegerField(choices=[(1, 'መስከረም'), (2, 'ጥቅምት'), (3, 'ህዳር'), (4, 'ታህሳስ'), (5, 'ጥር'), (6, 'የካቲት'), (7, 'መጋቢት'), (8, 'ሚያዝያ'), (9, 'ግንቦት'), (10, 'ሰኔ'), (11, 'ሐምሌ'), (12, 'ነሐሴ'), (13, 'ጳጉሜ')]),
        ),
    ]
