# Generated by Django 5.2.12 on 2026-07-05 08:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0018_alter_paymentdeadline_month'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentLinkToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('parent_phone', models.CharField(max_length=20)),
                ('jti', models.CharField(db_index=True, max_length=64, unique=True)),
                ('verification_code', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('first_device_fingerprint', models.CharField(blank=True, max_length=64, null=True)),
                ('first_seen_ip_prefix', models.CharField(blank=True, max_length=45, null=True)),
                ('otp_required', models.BooleanField(default=False)),
                ('otp_verified_at', models.DateTimeField(blank=True, null=True)),
                ('failed_attempts', models.PositiveSmallIntegerField(default=0)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='link_tokens', to='payments.payment')),
            ],
            options={
                'verbose_name': 'Payment Link Token',
                'verbose_name_plural': 'Payment Link Tokens',
                'indexes': [models.Index(fields=['jti'], name='payments_pa_jti_b610d6_idx')],
            },
        ),
    ]
