# Generated by Django 5.2.12 on 2026-07-09 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0019_paymentlinktoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentlinktoken',
            name='delivery_channel',
            field=models.CharField(choices=[('sms', 'SMS'), ('email', 'Email')], default='sms', help_text='Which channel this link was sent through — determines where the OTP is delivered.', max_length=10),
        ),
        migrations.AlterField(
            model_name='paymentdeadline',
            name='grade',
            field=models.IntegerField(blank=True, choices=[(1, 'Grade 1'), (2, 'Grade 2'), (3, 'Grade 3'), (4, 'Grade 4'), (5, 'Grade 5'), (6, 'Grade 6'), (7, 'Grade 7'), (8, 'Grade 8'), (9, 'Grade 9'), (10, 'Grade 10'), (11, 'Grade 11'), (12, 'Grade 12')], help_text='Leave blank to apply to all grades', null=True),
        ),
    ]
