# Generated by Django 5.2.12 on 2026-07-09 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0020_paymentlinktoken_delivery_channel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='receipt_token',
            field=models.UUIDField(blank=True, default=None, editable=False, help_text='Public token for the receipt page — generated only after payment is verified.', null=True, unique=True),
        ),
    ]
