# Generated by Django 5.2.12 on 2026-08-10 00:00
# ✅ Money-safety fix: previously, retrying a Chapa payment overwrote
# transaction_reference with no history kept. If Chapa later confirmed
# an OLDER attempt (webhook lag) after a retry had already overwritten
# the field, that webhook could never find the Payment row again — money
# deducted from a parent with no record of it anywhere in this system.
# This field preserves every tx_ref a Payment row has ever used so the
# webhook/verify/status lookups can always find it.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0021_payment_receipt_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='previous_tx_refs',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
