# Generated by Django 5.2.12 on 2026-08-12 00:00
# ✅ Jimma request #1 — fee exceptions & flexible payment plans.
# See StudentFeeOverride's docstring in payments/models.py for the full
# design rationale (why this is its own table and not Student.monthly_fee).

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0022_payment_previous_tx_refs'),
        ('students', '0006_studentdocument'),
        ('academics', '0007_subject_grade_alter_subject_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentFeeOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('override_type', models.CharField(choices=[('waiver', 'One-Time Waiver Amount (replaces all monthly fees for the year)'), ('partial', 'Partial Monthly Payment (reduced amount every month)')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, help_text="For 'waiver': the single total amount charged for the whole academic year. For 'partial': the reduced amount charged every month instead of the normal deadline amount.", max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('supporting_document', models.FileField(help_text='Required — kebele/NGO letter or other proof supporting this exception.', upload_to='fee_exception_documents/%Y/%m/')),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('deactivated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_overrides', to='academics.academicyear')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fee_overrides_created', to=settings.AUTH_USER_MODEL)),
                ('deactivated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fee_overrides_deactivated', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_overrides', to='students.student')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='studentfeeoverride',
            index=models.Index(fields=['student', 'academic_year', 'is_active'], name='payments_st_student_c1f4a1_idx'),
        ),
        migrations.AddConstraint(
            model_name='studentfeeoverride',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('student', 'academic_year'), name='unique_active_fee_override_per_student_year'),
        ),
    ]
