# Generated by Django 5.2.12
# ✅ Jimma request #2 — registration fees. See RegistrationFeeConfig and
# StudentRegistrationType docstrings in payments/models.py for the full
# design rationale, and PaymentDeadline.deadline_type for why month had
# to become nullable and unique_together needed deadline_type added.

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0023_studentfeeoverride'),
        ('students', '0006_studentdocument'),
        ('academics', '0007_subject_grade_alter_subject_options_and_more'),
        ('schools', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # --- PaymentDeadline changes -----------------------------------
        migrations.AlterUniqueTogether(
            name='paymentdeadline',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='paymentdeadline',
            name='deadline_type',
            field=models.CharField(
                choices=[('monthly', 'Monthly Fee'), ('registration', 'One-Time Registration Fee')],
                default='monthly',
                help_text="'monthly' = a regular monthly fee deadline. 'registration' = the one-time per-academic-year registration charge.",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name='paymentdeadline',
            name='month',
            field=models.IntegerField(
                blank=True,
                null=True,
                choices=[(1, 'መስከረም'), (2, 'ጥቅምት'), (3, 'ህዳር'), (4, 'ታህሳስ'), (5, 'ጥር'), (6, 'የካቲት'), (7, 'መጋቢት'), (8, 'ሚያዝያ'), (9, 'ግንቦት'), (10, 'ሰኔ'), (11, 'ሐምሌ'), (12, 'ነሐሴ'), (13, 'ጳጉሜ')],
            ),
        ),
        migrations.AlterField(
            model_name='paymentdeadline',
            name='amount',
            field=models.DecimalField(
                decimal_places=2, max_digits=10,
                help_text="For 'monthly': the amount due. For 'registration': informational only — the real per-student amount comes from RegistrationFeeConfig (new vs. continuing), not this field.",
            ),
        ),
        migrations.AlterField(
            model_name='paymentdeadline',
            name='grade',
            field=models.IntegerField(
                blank=True, null=True,
                choices=[(i, f'Grade {i}') for i in range(1, 13)],
                help_text="Leave blank to apply to all grades. Registration deadlines must leave this blank — registration isn't grade-specific.",
            ),
        ),
        migrations.AlterUniqueTogether(
            name='paymentdeadline',
            unique_together={('school', 'academic_year', 'deadline_type', 'month', 'grade')},
        ),

        # --- RegistrationFeeConfig --------------------------------------
        migrations.CreateModel(
            name='RegistrationFeeConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_student_amount', models.DecimalField(decimal_places=2, help_text='One-time registration fee for a NEW student this academic year.', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('continuing_student_amount', models.DecimalField(decimal_places=2, help_text='One-time registration fee for a CONTINUING/senior student this academic year.', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registration_fee_configs', to='academics.academicyear')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registration_fee_configs_created', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registration_fee_configs', to='schools.school')),
            ],
            options={
                'ordering': ['-academic_year'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='registrationfeeconfig',
            unique_together={('school', 'academic_year')},
        ),

        # --- StudentRegistrationType -------------------------------------
        migrations.CreateModel(
            name='StudentRegistrationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_type', models.CharField(choices=[('new', 'New Student'), ('continuing', 'Continuing/Senior Student')], max_length=20)),
                ('is_manual_override', models.BooleanField(default=False, help_text='True if an admin explicitly set this. False if it was auto-detected from payment history.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_registration_types', to='academics.academicyear')),
                ('set_by', models.ForeignKey(blank=True, help_text='Which admin set this manually. Null for auto-detected rows.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registration_types_set', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registration_types', to='students.student')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='studentregistrationtype',
            unique_together={('student', 'academic_year')},
        ),
    ]
