# Generated by Django 5.2.12 on 2026-08-13 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0024_registration_fees'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='studentfeeoverride',
            new_name='payments_st_student_412523_idx',
            old_name='payments_st_student_c1f4a1_idx',
        ),
    ]
