# Generated by Django 5.2.12 on 2026-07-10 00:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schools', '0011_school_grading_system_school_grade_scale'),
        ('students', '0005_student_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_id', models.CharField(blank=True, help_text='Format: SCHOOLCODE-STF-YEAR-SEQUENCE (e.g., FS-STF-2024-0001). Auto-generated if left blank.', max_length=50, null=True, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('photo', models.ImageField(blank=True, help_text='Staff/teacher profile photo (JPG, PNG)', null=True, upload_to='staff_photos/%Y/%m/')),
                ('role', models.CharField(choices=[('school_admin', 'School Admin'), ('teacher', 'Teacher'), ('registrar', 'Registrar'), ('accountant', 'Accountant / Payment Manager'), ('librarian', 'Librarian'), ('reporting_manager', 'Reporting Manager'), ('reminder_manager', 'Reminder Manager'), ('other', 'Other Staff')], default='teacher', max_length=30)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('national_id', models.CharField(blank=True, help_text='National ID / Kebele ID number', max_length=50)),
                ('hire_date', models.DateField()),
                ('base_salary', models.DecimalField(decimal_places=2, default=0, help_text='Monthly base salary in Birr — feeds the payroll module', max_digits=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('on_leave', 'On Leave'), ('terminated', 'Terminated')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_members', to='schools.school')),
                ('user', models.OneToOneField(blank=True, help_text='Linked login account, if this staff member has portal/app access', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['first_name', 'last_name'],
            },
        ),
        migrations.AddIndex(
            model_name='staffmember',
            index=models.Index(fields=['staff_id'], name='staff_staff_staff_i_2f5c1a_idx'),
        ),
        migrations.AddIndex(
            model_name='staffmember',
            index=models.Index(fields=['role'], name='staff_staff_role_5b6b8e_idx'),
        ),
        migrations.AddIndex(
            model_name='staffmember',
            index=models.Index(fields=['status'], name='staff_staff_status_9d3a2f_idx'),
        ),
        migrations.CreateModel(
            name='TeacherClassAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.IntegerField(choices=[(1, 'Grade 1'), (2, 'Grade 2'), (3, 'Grade 3'), (4, 'Grade 4'), (5, 'Grade 5'), (6, 'Grade 6'), (7, 'Grade 7'), (8, 'Grade 8'), (9, 'Grade 9'), (10, 'Grade 10'), (11, 'Grade 11'), (12, 'Grade 12')])),
                ('section', models.CharField(blank=True, help_text="e.g. 'A' — leave blank if this teacher covers the whole grade regardless of section", max_length=10)),
                ('subject_name', models.CharField(max_length=100)),
                ('academic_year', models.CharField(blank=True, help_text="e.g. '2018 E.C.'", max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_assignments', to='schools.school')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_assignments', to='staff.staffmember')),
            ],
            options={
                'ordering': ['grade', 'section', 'subject_name'],
                'unique_together': {('staff', 'grade', 'section', 'subject_name', 'academic_year')},
            },
        ),
    ]
