# Generated by Django 5.2.12 on 2026-07-17 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_homeroomassignment_subject'),
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherclassassignment',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_assignments', to='academics.subject'),
        ),
        migrations.AlterUniqueTogether(
            name='teacherclassassignment',
            unique_together={('staff', 'grade', 'section', 'subject', 'academic_year')},
        ),
        migrations.RemoveField(
            model_name='teacherclassassignment',
            name='subject_name',
        ),
        migrations.AlterModelOptions(
            name='teacherclassassignment',
            options={'ordering': ['grade', 'section', 'subject__name']},
        ),
    ]
