# Generated by Django 5.2.12 on 2026-07-24 09:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_alter_teacherclassassignment_options_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='staffmember',
            new_name='staff_staff_staff_i_d27e17_idx',
            old_name='staff_staff_staff_i_2f5c1a_idx',
        ),
        migrations.RenameIndex(
            model_name='staffmember',
            new_name='staff_staff_role_2ce707_idx',
            old_name='staff_staff_role_5b6b8e_idx',
        ),
        migrations.RenameIndex(
            model_name='staffmember',
            new_name='staff_staff_status_28b777_idx',
            old_name='staff_staff_status_9d3a2f_idx',
        ),
        migrations.AlterField(
            model_name='staffmember',
            name='base_salary',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Monthly base salary in Birr — feeds the payroll module', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
