# Generated by Django 5.2.12 on 2026-08-19 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0004_staff_hr_module'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='staffcareerevent',
            new_name='staff_staff_staff_i_500544_idx',
            old_name='staff_staff_staff_i_c9d4e2_idx',
        ),
        migrations.RenameIndex(
            model_name='staffdocument',
            new_name='staff_staff_staff_i_0eb6c4_idx',
            old_name='staff_staff_staff_i_8a2c11_idx',
        ),
    ]
