# Generated by Django 5.2.12 on 2026-05-01 09:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('PAYMENT_VERIFY', 'Payment Verification'), ('STUDENT_CREATE', 'Student Created'), ('STUDENT_EDIT', 'Student Edited'), ('STUDENT_DELETE', 'Student Deleted'), ('DEADLINE_CREATE', 'Deadline Created'), ('DEADLINE_EDIT', 'Deadline Edited'), ('DEADLINE_DELETE', 'Deadline Deleted'), ('SLIP_VERIFY', 'Slip Verified'), ('SLIP_REJECT', 'Slip Rejected'), ('SCHOOL_APPROVE', 'School Approved'), ('SCHOOL_REJECT', 'School Rejected'), ('SETTINGS_CHANGE', 'Settings Changed')], max_length=50)),
                ('details', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', '-timestamp'], name='common_audi_user_id_e20287_idx'), models.Index(fields=['action'], name='common_audi_action_288430_idx'), models.Index(fields=['timestamp'], name='common_audi_timesta_4ebe40_idx')],
            },
        ),
    ]
